### ISSUE TITLE
accelerate simulation by cuda

### ISSUE THREAD

**Issue by dutjyf** [autonomousvision/tuplan_garage#38]
Hello,
I run simulation by using cpu, but the speed is slowly.
I see this code in  `pdm_open_planer.py`
```python
        self._device = "cpu"
        self._model = LightningModuleWrapper.load_from_checkpoint(
            checkpoint_path,
            model=model,
            map_location=self._device,
        ).model
``` 
I change device `cpu` to `cuda:0`
but have bug about tensors have two different device `cpu` and `cuda:0`
so I want to ask if you use cuda to accelerate simulation process or use`cpu` run it.
and how to change cofing to use `cuda:0`
Thanks for your help!

**Comment by DanielDauner** [comment]
Hi @dutjyf, the standard setting is to use `cpu`. Simulation is generally fastest with `worker=ray_distributed`, where scenario simulations are parallelized over your _n_ logical cores. Enabling cuda in this simulation mode would require loading the model weights _n_ times onto your gpu, which is infeasible. If you use `worker=sequential`, you should be able to load onto the `cuda:0` device with an increase in speed relative to `cpu`. 

I hope that helped. Let me know if you have further questions!

**Comment by dutjyf** [comment]
Thanks for your reply.
I change the cofing `self._device = "cuda:0"` and `worker=sequential` but have this problem
```
 'Traceback (most recent call last):
  File "/home/wjl/jyf/nuplan-devkit/nuplan/planning/simulation/runner/executor.py", line 27, in run_simulation
    return sim_runner.run()
  File "/home/wjl/jyf/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 113, in run
    trajectory = self.planner.compute_trajectory(planner_input)
  File "/home/wjl/jyf/nuplan-devkit/nuplan/planning/simulation/planner/abstract_planner.py", line 108, in compute_trajectory
    raise e
  File "/home/wjl/jyf/nuplan-devkit/nuplan/planning/simulation/planner/abstract_planner.py", line 105, in compute_trajectory
    trajectory = self.compute_planner_trajectory(current_input)
  File "/home/wjl/jyf/tuplan_garage/tuplan_garage/planning/simulation/planner/pdm_planner/pdm_open_planner.py", line 115, in compute_planner_trajectory
    predictions = self._model.forward({"pdm_features": pdm_feature})
  File "/home/wjl/jyf/tuplan_garage/tuplan_garage/planning/training/modeling/models/pdm_open_model.py", line 166, in forward
    ego_feats_enc, _ = self.ego_enc(ego_feats)
  File "/home/wjl/anaconda3/envs/nuplan/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wjl/anaconda3/envs/nuplan/lib/python3.9/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/wjl/anaconda3/envs/nuplan/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wjl/anaconda3/envs/nuplan/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/wjl/anaconda3/envs/nuplan/lib/python3.9/site-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument mat2 in method wrapper_mm)
```
so I want to ask if have some solutions to deal with it

**appendix**
`defalut_simulation.yaml`
```
# Progress Visualization
enable_simulation_progress_bar: true # Show for every simulation its progress

# Simulation Setup
simulation_history_buffer_duration: 2.0  # [s] The look back duration to initialize the simulation history buffer with

# Number (or fractional, e.g., 0.25) of GPUs available for single simulation (per scenario and planner).
# This number can also be < 1 because we allow multiple models to be loaded into a single GPU.
# In case this number is 0 or null, no GPU is used for simulation and all cpu cores are leveraged
# Note, that the user have to make sure that if a number < 1 is chosen, the model will fit 1 / num_gpus into GPU memory
number_of_gpus_allocated_per_simulation: 1

# This number specifies number of CPU threads that are used for simulation
# In case this is null, then each simulation will use unlimited resources.
# That will typically swamp the host computer, leading to slowdowns and failure.
number_of_cpus_allocated_per_simulation: 

# Set false to disable metric computation
run_metric: true

# Set to rerun metrics with existing simulation logs without setting run_metric to false.
simulation_log_main_path: null

# If false, continue running the simulation even it a scenario has failed
exit_on_failure: false

# Maximum number of workers to be used for running simulation callbacks outside the main process
max_callback_workers: 1

# Disable callback parallelization when using the Sequential worker. By default, when running with the sequential worker,
# on_simulation_end callbacks are not submitted to a parallel worker.
disable_callback_parallelization: true

# Distributed processing mode. If multi-node simulation is enable, this parameter selects how the scenarios distributed
# to each node. The modes are:
#  - SCENARIO_BASED: Works in two stages, first getting a list of all, scenarios to process, then breaking up that
#                    list and distributing across the workers
#  - LOG_FILE_BASED: Works in a single stage, breaking up the scenarios based on what log file they are in and
#                    distributing the number of log files evenly across all workers
#  - SINGLE_NODE: Does no distribution, processes all scenarios in config
distributed_mode: 'SCENARIO_BASED'
```
`default_common.yaml`
```
defaults:
  # Add common items
  - scenario_builder: nuplan_mini
  - scenario_filter: one_continuous_log
  - model: null
  # Worker that is used to run simulations
  - worker: sequential #ray_distributed single_machine_thread_pool
···

**Comment by DanielDauner** [comment]
Hi, I got the same error. It seems that the model is not correctly loaded on the GPU. You can fix it by adding `.to(self._device)` in the model initialization:

```python
self._model = LightningModuleWrapper.load_from_checkpoint(
    checkpoint_path,
    model=model,
    map_location=self._device,
).model.to(self._device)
```

We might incorporate this fix in a future update. However, I couldn't achieve a notable speed-up. If your goal is to simulate many scenarios as fast as possible, I think `worker=ray_distributed` combined with `cpu` will be faster. I might be wrong. 

I am closing this issue for now. Let me know if you have further questions!
