### ISSUE TITLE
 Error loading module '.......pdm_closed_planner.PDMClosedPlanner'

### ISSUE THREAD

**Issue by invinciblenuonuo** [autonomousvision/tuplan_garage#58]
When I run  `sim_pdm_closed.sh`  , error occurred：
But I successfully run  `idm_planner`

```shell
Error executing job with overrides: ['+simulation=closed_loop_reactive_agents', 'planner=pdm_closed_planner', 'scenario_filter=val14_split', 'scenario_builder=nuplan']
Traceback (most recent call last):
  File "/home/cpns/Chen/apps/envs/PDM/lib/python3.9/site-packages/hydra/_internal/utils.py", line 560, in _locate
    module = import_module(mod)
  File "/home/cpns/Chen/apps/envs/PDM/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1027, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _sanity_check
ValueError: Empty module name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cpns/Chen/nuplan-devkit/nuplan/planning/script/run_simulation.py", line 110, in main
    run_simulation(cfg=cfg)
  File "/home/cpns/Chen/nuplan-devkit/nuplan/planning/script/run_simulation.py", line 66, in run_simulation
    runners = build_simulations(
  File "/home/cpns/Chen/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py", line 90, in build_simulations
    planners = build_planners(cfg.planner, scenario)
  File "/home/cpns/Chen/nuplan-devkit/nuplan/planning/script/builders/planner_builder.py", line 58, in build_planners
    return [_build_planner(planner, scenario) for planner in planner_cfg.values()]
  File "/home/cpns/Chen/nuplan-devkit/nuplan/planning/script/builders/planner_builder.py", line 58, in <listcomp>
    return [_build_planner(planner, scenario) for planner in planner_cfg.values()]
  File "/home/cpns/Chen/nuplan-devkit/nuplan/planning/script/builders/planner_builder.py", line 23, in _build_planner
    if is_target_type(planner_cfg, MLPlanner):
  File "/home/cpns/Chen/nuplan-devkit/nuplan/planning/script/builders/utils/utils_type.py", line 23, in is_target_type
    return bool(_locate(cfg._target_) == target_type)
  File "/home/cpns/Chen/apps/envs/PDM/lib/python3.9/site-packages/hydra/_internal/utils.py", line 563, in _locate
    raise ImportError(f"Error loading module '{path}'") from e
ImportError: Error loading module 'tuplan_garage.planning.simulation.planner.pdm_planner.pdm_closed_planner.PDMClosedPlanner'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

sim_pdm_closed.sh : 
```shell
SPLIT=val14_split
CHALLENGE=closed_loop_reactive_agents # open_loop_boxes, closed_loop_nonreactive_agents, closed_loop_reactive_agents
CHECKPOINT=/home/cpns/Chen/paper/tuplan_garage/checkpoint/pdm_open_checkpoint.ckpt

python $NUPLAN_DEVKIT_ROOT/nuplan/planning/script/run_simulation.py \
+simulation=$CHALLENGE \
planner=pdm_open_planner \
planner.pdm_open_planner.checkpoint_path=$CHECKPOINT \
scenario_filter=$SPLIT \
scenario_builder=nuplan \
hydra.searchpath="[file:///home/cpns/Chen/paper/tuplan_garage/tuplan_garage/planning/script/config/common,file:///home/cpns/Chen/paper/tuplan_garage/tuplan_garage/planning/script/config/simulation,file:///home/cpns/Chen/nuplan-devkit/nuplan/planning/script/config/common,file:///home/cpns/Chen/nuplan-devkit/nuplan/planning/script/experiments]"

```

**Comment by DanielDauner** [comment]
Hi @invinciblenuonuo 

Have you installed `tuplan_garage` as an editable pip packed in your `nuplan` conda environment (see [1. Installation](https://github.com/autonomousvision/tuplan_garage?tab=readme-ov-file#1-installation))? You can install the `tuplan_garage` with `pip install -e .`, similar to the recommended install of the `nuplan-devkit` (see [docs](https://nuplan-devkit.readthedocs.io/en/latest/installation.html#option-b-install-pip-package-from-local)).

After install, you can run the simulation with the searchpaths:
```bash 
…
hydra.searchpath="[pkg://tuplan_garage.planning.script.config.common, pkg://tuplan_garage.planning.script.config.simulation, pkg://nuplan.planning.script.config.common, pkg://nuplan.planning.script.experiments]" 
```

Best,
Daniel

**Comment by invinciblenuonuo** [comment]
I have followed the  nuplan doc `Option B: Install PIP package from local` and installed the nuplan-devkit  and setup the enviroment as:
```shell
export PYTHONPATH="${PYTHONPATH}:/home/cpns/Chen/nuplan-devkit"
export NUPLAN_DATA_ROOT="/home/cpns/Chen/nuplan/dataset"
export NUPLAN_MAPS_ROOT="/home/cpns/Chen/nuplan/dataset/maps"
export NUPLAN_DB_FILES="/home/cpns/Chen/nuplan/dataset/nuplan-v1.1/splits/mini"
export NUPLAN_EXP_ROOT="/home/cpns/Chen//nuplan/exp"
export NUPLAN_DEVKIT_ROOT="/home/cpns/Chen/nuplan-devkit"
``` 
When I run `pip install -e .` ,error occurred:
```shell
ERROR: Could not find a version that satisfies the requirement nuplan-devkit==1.2.2 (from tuplan-garage) (from versions: none)
```
So I comment the code `nuplan-devkit==1.2.2` ,because I think the nuplan-devkit is installed locally.
Then I run  `pip install -e .` 

```shell
Obtaining file:///home/cpns/Chen/paper/tuplan_garage
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scikit-learn==1.2.2 in /home/cpns/Chen/apps/lib/python3.11/site-packages (from tuplan-garage==1.0.0) (1.2.2)
Requirement already satisfied: positional-encodings==6.0.1 in /home/cpns/Chen/apps/lib/python3.11/site-packages (from tuplan-garage==1.0.0) (6.0.1)
Requirement already satisfied: numpy in /home/cpns/Chen/apps/lib/python3.11/site-packages (from positional-encodings==6.0.1->tuplan-garage==1.0.0) (1.26.4)
Requirement already satisfied: scipy>=1.3.2 in /home/cpns/Chen/apps/lib/python3.11/site-packages (from scikit-learn==1.2.2->tuplan-garage==1.0.0) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /home/cpns/Chen/apps/lib/python3.11/site-packages (from scikit-learn==1.2.2->tuplan-garage==1.0.0) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/cpns/Chen/apps/lib/python3.11/site-packages (from scikit-learn==1.2.2->tuplan-garage==1.0.0) (2.2.0)
Installing collected packages: tuplan-garage
  Attempting uninstall: tuplan-garage
    Found existing installation: tuplan-garage 1.0.0
    Uninstalling tuplan-garage-1.0.0:
      Successfully uninstalled tuplan-garage-1.0.0
      Running setup.py develop for tuplan-garage
      Successfully installed tuplan-garage-1.0.0
```

But when I use 
```shell
hydra.searchpath="[pkg://tuplan_garage.planning.script.config.common, pkg://tuplan_garage.planning.script.config.simulation, pkg://nuplan.planning.script.config.common, pkg://nuplan.planning.script.experiments]" 
```

Error occurred 
```shell
/home/cpns/Chen/apps/envs/PDM/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py:213: UserWarning: provider=hydra.searchpath in command-line, path=tuplan_garage.planning.script.config.common is not available.
  warnings.warn(
/home/cpns/Chen/apps/envs/PDM/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py:213: UserWarning: provider=hydra.searchpath in command-line, path=tuplan_garage.planning.script.config.simulation is not available.
  warnings.warn(
In 'default_simulation': Could not find 'planner/pdm_closed_planner'

Available options in 'planner':
	idm_planner
	log_future_planner
	ml_planner
	remote_planner
	simple_planner
Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=file:///home/cpns/Chen/nuplan-devkit/nuplan/planning/script/config/simulation
	provider=hydra.searchpath in command-line, path=pkg://tuplan_garage.planning.script.config.common
	provider=hydra.searchpath in command-line, path=pkg://tuplan_garage.planning.script.config.simulation
	provider=hydra.searchpath in command-line, path=pkg://nuplan.planning.script.config.common
	provider=hydra.searchpath in command-line, path=pkg://nuplan.planning.script.experiments
	provider=schema, path=structured://
```

So I have to change the hydra.searchpath to 
```shell
hydra.searchpath="[file:///home/cpns/Chen/paper/tuplan_garage/tuplan_garage/planning/script/config/common,file:///home/cpns/Chen/paper/tuplan_garage/tuplan_garage/planning/script/config/simulation,file:///home/cpns/Chen/nuplan-devkit/nuplan/planning/script/config/common,file:///home/cpns/Chen/nuplan-devkit/nuplan/planning/script/experiments]"
```

And the `In 'default_simulation': Could not find 'planner/pdm_closed_planner'` fixed , But new error occurred
```shell
ImportError: Error loading module 'tuplan_garage.planning.simulation.planner.pdm_planner.pdm_closed_planner.PDMClosedPlanner'
```

**Comment by DanielDauner** [comment]
Hi @invinciblenuonuo 

I am a bit confused here. To run `tuplan_garage`, you first need to install nuPlan as described in their [docs](https://nuplan-devkit.readthedocs.io/en/latest/installation.html), i.e. clone the repo, create the nuPlan conda environment, and install `nuplan-devkit` in the conda environment as editable pip package. 

Afterwards, you need to install `tuplan_garage` as an editable pip package (thus the requirement `nuplan-devkit==1.2.2` should not fail).

Could you create a fresh new conda environment and install both `nuplan-devkit` and `tuplan_garage` as editable pip packages? 

Best,
Daniel

**Comment by invinciblenuonuo** [comment]
Thank you for your reply. The problem lies in the fact that when using pip, it called the local pip instead of the pip in the conda environment.
